#!/usr/bin/env python

import click

@click.command()
@click.argument('data')
def change_readnames(data):
  """ Adds "\1" or "\2" to paired end read names in fastq file generated by
  Illumina Hiseq. This format is needed for input for Trans-ABySS"""

  # read in original fastq file
  f = open(data)

  count = 0
  output_file = open('sequence_new.fq', 'w') # change 'sequence_new.fq' to the name you want for your new fastq file
  for line in f:
    if line.startswith("@"):
        changed_string = line + "\\1\n" # to add to reverse fastq change "\1" to "\2"
        output_file.write(changed_string)
        count += 1
    else:
        output_file.write(line)
  output_file.close()

  print(count, "reads in", data)

if __name__ == '__main__':
      change_readnames()
